# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/unkid/qtproj/try/sett.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_setSettings(object):
    def setupUi(self, setSettings):
        setSettings.setObjectName("setSettings")
        setSettings.resize(424, 513)
        self.verticalLayout = QtWidgets.QVBoxLayout(setSettings)
        self.verticalLayout.setObjectName("verticalLayout")
        self.dirLabel = QtWidgets.QLabel(setSettings)
        self.dirLabel.setObjectName("dirLabel")
        self.verticalLayout.addWidget(self.dirLabel)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.dirEdit = QtWidgets.QLineEdit(setSettings)
        self.dirEdit.setObjectName("dirEdit")
        self.horizontalLayout_2.addWidget(self.dirEdit)
        self.dirBtn = QtWidgets.QPushButton(setSettings)
        self.dirBtn.setObjectName("dirBtn")
        self.horizontalLayout_2.addWidget(self.dirBtn)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.repLabel = QtWidgets.QLabel(setSettings)
        self.repLabel.setObjectName("repLabel")
        self.verticalLayout.addWidget(self.repLabel)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.checkBox1 = QtWidgets.QCheckBox(setSettings)
        self.checkBox1.setChecked(False)
        self.checkBox1.setObjectName("checkBox1")
        self.verticalLayout_2.addWidget(self.checkBox1)
        self.checkBox2 = QtWidgets.QCheckBox(setSettings)
        self.checkBox2.setObjectName("checkBox2")
        self.verticalLayout_2.addWidget(self.checkBox2)
        self.checkBox3 = QtWidgets.QCheckBox(setSettings)
        self.checkBox3.setObjectName("checkBox3")
        self.verticalLayout_2.addWidget(self.checkBox3)
        self.checkBox4 = QtWidgets.QCheckBox(setSettings)
        self.checkBox4.setChecked(True)
        self.checkBox4.setObjectName("checkBox4")
        self.verticalLayout_2.addWidget(self.checkBox4)
        self.checkBox5 = QtWidgets.QCheckBox(setSettings)
        self.checkBox5.setChecked(True)
        self.checkBox5.setObjectName("checkBox5")
        self.verticalLayout_2.addWidget(self.checkBox5)
        self.checkBox6 = QtWidgets.QCheckBox(setSettings)
        self.checkBox6.setChecked(True)
        self.checkBox6.setObjectName("checkBox6")
        self.verticalLayout_2.addWidget(self.checkBox6)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.formatLabel = QtWidgets.QLabel(setSettings)
        self.formatLabel.setObjectName("formatLabel")
        self.verticalLayout.addWidget(self.formatLabel)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.aviCheck = QtWidgets.QCheckBox(setSettings)
        self.aviCheck.setChecked(True)
        self.aviCheck.setObjectName("aviCheck")
        self.horizontalLayout_3.addWidget(self.aviCheck)
        self.mp4Check = QtWidgets.QCheckBox(setSettings)
        self.mp4Check.setObjectName("mp4Check")
        self.horizontalLayout_3.addWidget(self.mp4Check)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.saveBtn = QtWidgets.QPushButton(setSettings)
        self.saveBtn.setObjectName("saveBtn")
        self.horizontalLayout_4.addWidget(self.saveBtn)
        self.exitBtn = QtWidgets.QPushButton(setSettings)
        self.exitBtn.setObjectName("exitBtn")
        self.horizontalLayout_4.addWidget(self.exitBtn)
        self.verticalLayout.addLayout(self.horizontalLayout_4)

        self.retranslateUi(setSettings)
        QtCore.QMetaObject.connectSlotsByName(setSettings)

    def retranslateUi(self, setSettings):
        _translate = QtCore.QCoreApplication.translate
        setSettings.setWindowTitle(_translate("setSettings", "Настройки обработки"))
        self.dirLabel.setText(_translate("setSettings", "Выберите путь до папки сохранения и имя нового файла"))
        self.dirEdit.setText(_translate("setSettings", "output/"))
        self.dirBtn.setText(_translate("setSettings", "Обзор"))
        self.repLabel.setText(_translate("setSettings", "Выберите пункты, которые хотите видеть в отчёте"))
        self.checkBox1.setText(_translate("setSettings", "Процент кадров с негативными эмоциями"))
        self.checkBox2.setText(_translate("setSettings", "Процент кадров с нейтральными эмоциями"))
        self.checkBox3.setText(_translate("setSettings", "Процент кадров с положительными эмоциями"))
        self.checkBox4.setText(_translate("setSettings", "Процент кадров каждой эмоции"))
        self.checkBox5.setText(_translate("setSettings", "Процент кадров с активными учащимися"))
        self.checkBox6.setText(_translate("setSettings", "Процент кадров с отвлекшимися учениками"))
        self.formatLabel.setText(_translate("setSettings", "Выберите формат, в котором хотите сохранить видео"))
        self.aviCheck.setText(_translate("setSettings", "AVI"))
        self.mp4Check.setText(_translate("setSettings", "MP4"))
        self.saveBtn.setText(_translate("setSettings", "Сохранить"))
        self.exitBtn.setText(_translate("setSettings", "Выход"))
