# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/unkid/qtproj/try/testcap.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 297)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.settLabel = QtWidgets.QLabel(self.centralwidget)
        self.settLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.settLabel.setObjectName("settLabel")
        self.verticalLayout.addWidget(self.settLabel)
        self.brightLabel = QtWidgets.QLabel(self.centralwidget)
        self.brightLabel.setObjectName("brightLabel")
        self.verticalLayout.addWidget(self.brightLabel)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.brightSlider = QtWidgets.QSlider(self.centralwidget)
        self.brightSlider.setOrientation(QtCore.Qt.Horizontal)
        self.brightSlider.setObjectName("brightSlider")
        self.verticalLayout_3.addWidget(self.brightSlider)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.brightVal1 = QtWidgets.QLabel(self.centralwidget)
        self.brightVal1.setObjectName("brightVal1")
        self.horizontalLayout_5.addWidget(self.brightVal1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        self.brightVal2 = QtWidgets.QLabel(self.centralwidget)
        self.brightVal2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.brightVal2.setObjectName("brightVal2")
        self.horizontalLayout_5.addWidget(self.brightVal2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        self.contrLabel = QtWidgets.QLabel(self.centralwidget)
        self.contrLabel.setObjectName("contrLabel")
        self.verticalLayout.addWidget(self.contrLabel)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.contrSlider = QtWidgets.QSlider(self.centralwidget)
        self.contrSlider.setMaximum(30)
        self.contrSlider.setSingleStep(1)
        self.contrSlider.setProperty("value", 10)
        self.contrSlider.setOrientation(QtCore.Qt.Horizontal)
        self.contrSlider.setObjectName("contrSlider")
        self.verticalLayout_2.addWidget(self.contrSlider)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.contrVal1 = QtWidgets.QLabel(self.centralwidget)
        self.contrVal1.setObjectName("contrVal1")
        self.horizontalLayout_3.addWidget(self.contrVal1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.contrVal2 = QtWidgets.QLabel(self.centralwidget)
        self.contrVal2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.contrVal2.setObjectName("contrVal2")
        self.horizontalLayout_3.addWidget(self.contrVal2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.startBtn = QtWidgets.QPushButton(self.centralwidget)
        self.startBtn.setObjectName("startBtn")
        self.horizontalLayout.addWidget(self.startBtn)
        self.stopBtn = QtWidgets.QPushButton(self.centralwidget)
        self.stopBtn.setObjectName("stopBtn")
        self.horizontalLayout.addWidget(self.stopBtn)
        self.saveSett = QtWidgets.QPushButton(self.centralwidget)
        self.saveSett.setObjectName("saveSett")
        self.horizontalLayout.addWidget(self.saveSett)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.exitBtn = QtWidgets.QPushButton(self.centralwidget)
        self.exitBtn.setObjectName("exitBtn")
        self.verticalLayout.addWidget(self.exitBtn)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Тестовая запись"))
        self.settLabel.setText(_translate("MainWindow", "Настройки яркости и контрастности"))
        self.brightLabel.setText(_translate("MainWindow", "Яркость"))
        self.brightVal1.setText(_translate("MainWindow", "0"))
        self.label_2.setText(_translate("MainWindow", ""))
        self.brightVal2.setText(_translate("MainWindow", "100"))
        self.contrLabel.setText(_translate("MainWindow", "Контрастность"))
        self.contrVal1.setText(_translate("MainWindow", "0"))
        self.label.setText(_translate("MainWindow", ""))
        self.contrVal2.setText(_translate("MainWindow", "3"))
        self.startBtn.setText(_translate("MainWindow", "Начать запись"))
        self.stopBtn.setText(_translate("MainWindow", "Закончить запись"))
        self.saveSett.setText(_translate("MainWindow", "Сохранить параметры"))
        self.exitBtn.setText(_translate("MainWindow", "Выход"))
